version: "3.7"

services:

  # Backend API
  todo-app-vue-api:
    container_name: backend
    build: ./ # Use Dockerfile to build the container
    command: npm start
    working_dir: /usr/src/todo-app-vue-api
    ports:
      - "3000:3000" # Map container port 3000 to port 3000 of local machine
    environment:
      DB_URI: postgres://api_user:password@postgres:5432/todos_api
    links:
      - postgres
    volumes: 
      - ./:/usr/src/todo-app-vue-api # Map local files to files in the container, to listen to changes in local files
  
  # Postgres. Docs: https://hub.docker.com/_/postgres/
  postgres:
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos_api
      POSTGRES_HOST: postgres
    # container_name: postgres
    build: ./postgres
    # image: postgres
    ports:
      - "5432:5432"