version: "3.7"

services:
  todo-app-vue-api:
    container_name: backend
    build: ./ # Use Dockerfile to build the container
    command: npm start
    working_dir: /usr/src/todo-app-vue-api
    ports:
      - "3000:3000" # Map container port 3000 to port 3000 of local machine
    # volumes: 
    #   - ./:/usr/src/todo-app-vue-api # Map local files to files in the container, to listen to changes in local files